---
name: img-search
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - django
  - django-crispy-forms
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-image
  - psycopg2
  - opencv
  - pyfiglet
  - tabulate
  - termcolor
  - scikit-learn
  - cvxopt
